### ISSUE TITLE
How to apply speciesprimer in my scenario?

### ISSUE THREAD

**Issue by Anto007** [biologger/speciesprimer#16]
This sounds like a very interesting tool. I'm wondering if this tool can be used to design PCR primers targeting a (single-copy) gene sequence that is specific to my bacterial species of interest but will not cross-amplify sequences from any other bacteria in the NCBI nt database; I believe this is anyways what this tool is intended for from reading of your full paper? For example, I have sequenced one genome from a bacterium species that is present in my environment. I now would like to design qPCR primers to detect & quantify the abundance of this particular species (but not other species in the same genus or any other extant bacteria in the world) in my subsequent samplings of that environment (i.e., from community eDNA). I have already got available all the genomes from the bacterial species of interest and the full NCBI nt database and would appreciate any pointers as to how to best proceed with using your tool speciesprimer in this particular scenario. Also, I'm not that familiar with Docker and I'm getting the below issue when trying to install docker as per the instructions that you suggested on the homepage. It simply gets stuck for a long time at `Handling signal: winch` step and doesn't proceed further. I'm using Ubuntu 16.04.7 LTS on a machine with 64 cores, 243 GB available (free) memory and several terrabytes of (free) storage space and currently, this docker task is the only job running on this machine. Thanks again in advance

```
sudo docker run   -v $HOME/blastdb:/blastdb   -v $HOME/primerdesign:/primerdesign   -p 5000:5000 -p 9001:9001   --name speciesprimer biologger/speciesprimer
[2022-04-14 13:16:35 +0000] [1] [INFO] Starting gunicorn 20.0.0
[2022-04-14 13:16:35 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2022-04-14 13:16:35 +0000] [1] [INFO] Using worker: sync
[2022-04-14 13:16:35 +0000] [9] [INFO] Booting worker with pid: 9
[2022-04-14 13:16:59 +0000] [1] [INFO] Handling signal: winch
[2022-04-14 13:16:59 +0000] [1] [INFO] Handling signal: winch
[2022-04-14 13:26:15 +0000] [1] [INFO] Handling signal: winch
[2022-04-14 13:26:15 +0000] [1] [INFO] Handling signal: winch 
```

**Comment by Anto007** [comment]
Thank you so much for your kind response and the detailed info; I tried opening a new terminal and typed the below as you suggested but I'm getting `command not found` error as below. Via the browser mode, I'm unable to connect to the server. Thanks again in advance

```
jbn@kw1111:~$ sudo docker exec -it speciesprimer /bin/bash
[sudo] password for jbn: 
root@d1c4e6264923:/primerdesign# speciesprimer -t Methylophaga_frappieri --nolist --qc_gene tuf --email jbnrodri@gmail.com --blastdbv5
bash: speciesprimer: command not found
```

**Comment by Anto007** [comment]
I just realized that adding a `.py` is needed for speciesprimer but when I try giving the path to the NCBI nt database using --customdb, I get the below error message. I would like to try and avoid not only other bacteria but other life-forms (eukaryotes) that may be present in that environment

```
speciesprimer.py -t Methylophaga_frappieri --nolist --qc_gene tuf --email jbnrodri@gmail.com --customdb /home/jbn/ncbi-db/nt
Traceback (most recent call last):
  File "/pipeline/speciesprimer.py", line 4205, in <module>
    main()
  File "/pipeline/speciesprimer.py", line 4164, in main
    H.BLASTDB_check(config)
  File "/pipeline/basicfunctions.py", line 482, in BLASTDB_check
    raise BlastDBError(msg)
basicfunctions.BlastDBError: No BLAST DB was found /home/jbn/ncbi-db/nt
```

**Comment by biologger** [comment]
Sorry, yes the file extension .py is needed.
The problem is that docker cannot access directly to the file system of the host. you have to mount the directory with the Blast DB into docker using the docker run command.

First you need to remove the old container before you can create a new one

```
sudo docker stop
sudo docker rm speciesprimer
```

Then create a new container with the correct db mount directory.

`sudo docker run -v /home/jbn/ncbi-db/nt:/blastdb   -v /home/jbn/primerdesign:/primerdesign   -p 5000:5000 -p 9001:9001   --name speciesprimer biologger/speciesprimer`

The nt db is the standard db so you don't need the custom db command

`speciesprimer.py -t Methylophaga_frappieri --nolist --qc_gene tuf --email jbnrodri@gmail.com`

add the '--blastdbv5'  flag if you downloaded the blast db recently, since the v5 db is the default since a while.

**Comment by Anto007** [comment]
Ah, I see! thanks again; I'm looking forward to citing your cool tool in my upcoming publications.
