### ISSUE TITLE
Could you record a video showing the whole process of using this software

### ISSUE THREAD

**Issue by Liu-senjun** [biologger/speciesprimer#19]
Dear teacher：
     I am a student who is very unfamiliar with biological information. I am currently committed to cultivating dozens of different bacteria. I want to design primer of each bacteria by qPCR to determine that they are different from other bacteria. After reading your article carefully, I found that the software designed in your article meets my primer design requirements. However, when I designed the primer according to the GUI of the operation manual you wrote, there will always be various problems, and the final result file is not obtained. Common errors are as shown below. “Traceback (most recent call last):
  File "/pipeline/gui/daemon/daemonize.py", line 75, in <module>
    main_daemon()
  File "/pipeline/gui/daemon/daemonize.py", line 56, in main_daemon
    d.start()
  File "/usr/local/lib/python3.5/dist-packages/mydaemon/__init__.py", line 107, in start
    self.run()
  File "/pipeline/gui/daemon/daemonclass.py", line 17, in run
    self.command()
  File "/pipeline/gui/daemon/daemonclass.py", line 50, in command
    speciesprimer.main(mode="auto")
  File "/pipeline/speciesprimer.py", line 4164, in main
    H.BLASTDB_check(config)
  File "/pipeline/basicfunctions.py", line 482, in BLASTDB_check
    raise BlastDBError(msg)
basicfunctions.BlastDBError: No BLAST DB was found nt
”.I want to know whether  you have recorded videos  to show readers how to use your software faster and more accurate by using your article data as an example or other examples? If so, can you provide me with a link? As a person who is very unfamiliar with biological information and computer science, if we can learn the use of this software through video, it will make us master this technology and method faster. Thank you so much! If there is no video, can you help me solve the problem of error? I have already downloaded  BLAST DB. And this errors appear when i use speciesprimer by GUI. Thank you very much for your patience to read  my problem description. I look forward to your answer. Thank you！

**Comment by biologger** [comment]
Hi, thanks for your kind message. 

Unfortunately, currently there is no video explaining the process of setting up the pipeline.

However, the relevant part of the error message is: "No BLAST DB was found nt"

If you have already downloaded the nt database make sure that the database is in the directory that was mounted as blastdb directory in the docker container. In the following example it is the $HOME/blastdb directory on the host computer.

```
  $ mkdir $HOME/primerdesign
  $ mkdir $HOME/blastdb
  $ sudo docker run \
      -v $HOME/blastdb:/blastdb \
      -v $HOME/primerdesign:/primerdesign \
      -p 5000:5000 -p 9001:9001 \
      --name speciesprimer biologger/speciesprimer
```
I hope this helps solving the problem.

**Comment by Liu-senjun** [comment]
Thanks for your sincerely enthusiastic answer. Yes, i have already downloaded the nt database on the host computer. Could you tell me how to make my database is in the directory  be mounted as blastdb directory in the docker container? Thank you very much! I look forward to your answer. Thank you！

**Comment by biologger** [comment]
In the docker run command the -v (--volume) parameter is the part where you have to add the path to the directory where your nt database was downloaded on your computer. 

for example my BLAST database is in the directory:
`/home/biologger/data/SpeciesPrimer_Support/blastdb`

in the container the pipeline looks for the BLAST DB in the directory
`/blastdb`

Therefore when you are setting up the container you need to run:

```
sudo docker run \
      -v /home/biologger/data/SpeciesPrimer_Support/blastdb:/blastdb \
      -v /home/biologger/primerdesign:/primerdesign \
      -p 5000:5000 -p 9001:9001 \
      --name speciesprimer biologger/speciesprimer
```
