### ISSUE TITLE
Decode the gene name from the results table

### ISSUE THREAD

**Issue by Lorenzomicro** [biologger/speciesprimer#7]
Good morning,
I finally got a 19 pair of primers for my Enterobacter kobei and I am very happy about it. 
But I have another question now ;)
In the _primer file, for every set of primer, a gene name is associated with them. In some case it correspond to a protein (wecD) and is possible to track it down and maybe use that as a criteria to reduce the number of primer to test. 
In other case is just a default name like g2895_1, g20472_3, g20472_3, g20556_2, g1516_4, g20637_2. Are this number something like hypothetical protein, so I can't associate them with any protein ?

Cheers
Lorenzo

**Comment by biologger** [comment]
Hi Lorenzo,

Yes, the primer names contain the name of the gene, in the case of g.... these are hypothetical proteins named "group_{number}"  by Prokka.

Cheers,
Matt

**Comment by Lorenzomicro** [comment]
Great!
Thanks Matt

Cheers
Lorenzo
