### ISSUE TITLE
gene_presence_absence.csv file interpretation

### ISSUE THREAD

**Issue by Lorenzomicro** [biologger/speciesprimer#8]
Good morning,

I like this software so much that I am asking you a question per week 😊. So, I know this software was created to produce species specific primers (and is working great on that) but I was wonder if, since I can add the genome of my strain inside the input list, if I can also use it to extract some strain specific primer.
After a run, I see that in the “Pangenome” folder there a file called gene_presence_absence.csv with a list of genes and in which one of the strain are they included. So, if I filter that with my strain and scroll down, I can see which gene is only included into my strain, and this is one step forward. 

Here it comes the issue. Let say that my gene is called “group_18946” (I suppose according to Prokka) and I got nothing inside the column “Non-unique Gene name”, there is a way to extract that sequence region from my strain?
I have import the gff file of my strain from the “gff_files” folder into my Windows program (Geneious) but I can only see CDS and other genes name but not any “group_XXX” among all the sequences. Is this because my program lost this kind of information? Or because the .gff is the wrong one to open and instead there is another file where to look for? Or maybe I should open the .gff  inside of Linux and look for group_18946 there?

I hope I was clear enough in the explanation of my doubt but if you need any other information I am at your disposal.

Best regards
Lorenzo

**Comment by biologger** [comment]
Hi Lorenzo,

I'm happy to hear you like it :)

You are right in the gene_presence_absence.csv file (Roary Pangenome output), the pan-genome genes and the information in which genomes they are present is accessible. Take the row of your gene name, if you scroll to the right from "Avg group size nuc" there are more columns (the column names are the input genome names), scroll until you find a value, there the strain genome name and the gene locus are given. e.g. GCF_900185885v1_01022 

In the corresponding ffn file (GCF_900185885v1_annotationdate) you can find the locus (GCF_900185885v1_01022) and the corresponding sequence, I am not familiar with Geneious but it works even in a simple text editor. The same locus ID (locus_tag) is also used in the gff files.

__StrainPrimer__ is actually something I've been working on, but unfortunately could not finish yet.

There is some experimental draft of it in the v2.2 beta version with a strains option in the command line.

		$ docker pull biologger/speciesprimer:v2.2-beta.4

However, the documentation and tests are not yet available and it is very likely that there are some bugs.

Cheers,
Matt
